server:
  port: 8080

jwt:
  secret: qwerty
  expirationMs: 3600000
  refreshExpirationMs: 86400000

github:
  client_id:
  client_secret:
  ## For test
#  expirationMs: 60000
#  refreshExpirationMs: 120000
client:
  url:
#spring:
#  datasource:
#    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1;sql.syntax_pgs=true
#    username: sa
#    password:
#    driverClassName: org.hsqldb.jdbc.JDBCDriver
#  jpa:
##    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: validate

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate