server:
  port: 8080

jwt:
  secret:
  expirationMs: 3600000
  refreshExpirationMs: 86400000

github:
  client_id:
  client_secret:
  ## For test
#  expirationMs: 60000
#  refreshExpirationMs: 120000

client:
  url: https://authapp-adeoluwa.netlify.app

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username:
    url:
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate