name: Test, Build & Deploy

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_build_publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Java Environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Update application.yml values
        uses: fjogeleit/yaml-update-action@main
        with:
          changes: |
            {
              "src/main/resources/application-prod.yml": {
                "jwt.secret": "${{ secrets.JWT_SECRET }}",
                "github.client_id": "${{ secrets.GH_CLIENT_ID }}",
                "github.client_secret": "${{ secrets.GH_CLIENT_SECRET }}",
                "spring.datasource.username": "${{ secrets.POSTGRES_USERNAME }}",
                "spring.datasource.url": "${{ secrets.POSTGRES_URL }}",
                "spring.datasource.password": "${{ secrets.POSTGRES_PASSWORD }}"
              },
              "src/main/resources/application.yml": {
                "spring.profiles.active": "prod"
              }
            }
          commitChange: false
          createPR: false
      - name: Test and Build Jar File
        run: mvn install
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/authApp-java-be
      - name: Docker push
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: docker push ${{ secrets.DOCKER_USER }}/authApp-java-be:latest


  pull_run_docker_image:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [test_build_publish_docker_image]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy Django BE
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or Public key of the server
          username: ${{secrets.SSH_USERNAME}} # User of server you want to ssh into

          ## Have to fix this there must be a better way
          script: |
            docker pull ${{ secrets.DOCKER_USER }}/authApp-java-be:latest

            docker stop authApp-java-be

            docker rm -f authApp-java-be

            docker run -d -p 8080:8080 --name authApp-java-be ${{ secrets.DOCKER_USER }}/authApp-java-be:latest